export const Questions = [
  {
    number: 1,
    type: "qcu",
    question: "Quelle est la syntaxe correcte pour définir une fonction avec un paramètre nommé optionnel en Dart ?",
    options: [
      "A. void maFonction(String nom, {int? age})",
      "B. void maFonction(String nom, [int age])",
      "C. void maFonction(String nom, optional int age)",
      "D. void maFonction(String nom, int age = null)",
    ],
    answers: ["A"],
  },
  {
    number: 2,
    type: "qcu",
    question: "Que se passe-t-il si on essaie d'accéder à une variable déclarée avec late avant qu'elle ne soit initialisée ?",
    options: [
      "A. La variable retourne null",
      "B. Une LateInitializationError est levée",
      "C. Le programme compile mais plante silencieusement",
      "D. La variable prend une valeur par défaut",
    ],
    answers: ["B"],
  },
  {
    number: 3,
    type: "qcu",
    question: "Quelle est la différence entre ?. et ! en Dart ?",
    options: [
      "A. ?. force le déballage, ! vérifie null",
      "B. ?. vérifie null avant accès, ! force le déballage",
      "C. Les deux sont identiques",
      "D. ?. est pour les entiers, ! pour les chaînes",
    ],
    answers: ["B"],
  },
  {
    number: 4,
    type: "qcu",
    question: "Quel est le résultat de ce code : String? nom; print(nom?.length ?? 0); ?",
    options: [
      "A. null", 
      "B. 0",
      "C. Une erreur de compilation",
      "D. Une exception à l'exécution",
    ],
    answers: ["B"],
  },
  {
    number: 5,
    type: "qcu",
    question: "Comment définir un constructeur nommé en Dart ?",
    options: [
      "A. MaClasse.monConstructeur(): super();",
      "B. constructor MaClasse.monConstructeur(){}",
      "C. MaClasse.monConstructeur(){}",
      "D. new MaClasse.monConstructeur(){}",
    ],
    answers: ["C"],
  },
  {
    number: 6,
    type: "qcu",
    question: "Quelle syntaxe permet de créer une fonction lambda qui retourne le carré d'un nombre ?",
    options: [
      "A. (x) => x * x",
      "B. lambda x: x * x",
      "C. function(x){ return x * x; }",
      "D. (x) -> x * x",
    ],
    answers: ["A"],
  },
  {
    number: 7,
    type: "qcu",
    question: "Que fait l'opérateur ?? en Dart ?",
    options: [
      "A. Vérifie l'égalité",
      "B. Retourne la valeur de droite si celle de gauche est nulle",
      "C. Effectue une division entière",
      "D. Compare deux objets",
    ],
    answers: ["B"],
  },
  {
    number: 8,
    type: "qcu",
    question: "Comment déclarer une liste qui peut contenir des éléments null en Dart ?",
    options: [
      "A. List<int?> nombres = [];",
      "B. List<int> nombres = [null];",
      "C. List<null> nombres = [];",
      "D. List<int>? nombres = [];",
    ],
    answers: ["A"],
  },
  {
    number: 9,
    type: "qcu",
    question: "Quelle est la syntaxe correcte pour un constructeur avec paramètres nommés obligatoires ?",
    options: [
      "A. MaClasse({String nom, int age})",
      "B. MaClasse({required String nom, required int age})",
      "C. MaClasse({mandatory String nom, mandatory int age})",
      "D. MaClasse({final String nom, final int age})",
    ],
    answers: ["B"],
  },
  {
    number: 10,
    type: "qcu",
    question: "Que fait le mot-clé late en Dart ?",
    options: [
      "A. Indique qu'une variable sera initialisée plus tard mais avant utilisation",
      "B. Retarde l'exécution d'une fonction",
      "C. Crée une variable constante",
      "D. Définit une variable statique",
    ],
    answers: ["A"],
  },
  {
    number: 11,
    type: "qcu",
    question: "Quel est le rôle de la fonction runApp() en Flutter ?",
    options: [
      "A. Lancer l'émulateur",
      "B. Compiler l'application",
      "C. Attacher le widget racine à l'écran",
      "D. Initialiser la base de données",
    ],
    answers: ["C"],
  },
  {
    number: 12,
    type: "qcu",
    question: "Quelle méthode doit obligatoirement être implémentée dans un StatelessWidget ?",
    options: [
      "A. createState()",
      "B. build()",
      "C. initState()",
      "D. dispose()",
    ],
    answers: ["B"],
  },
  {
    number: 13,
    type: "qcu",
    question: "Dans quel ordre sont appelées ces méthodes lors de la création d'un StatefulWidget ?",
    options: [
      "A. build() → createState() → initState()",
      "B. createState() → initState() → build()",
      "C. initState() → createState() → build()",
      "D. createState() → build() → initState()",
    ],
    answers: ["B"],
  },
  {
    number: 14,
    type: "qcu",
    question: "Que se passe-t-il si on modifie une variable d'état sans appeler setState() ?",
    options: [
      "A. L'interface se met à jour automatiquement",
      "B. L'interface ne se met pas à jour",
      "C. Une erreur est levée",
      "D. L'application redémarre",
    ],
    answers: ["B"],
  },
  {
    number: 15,
    type: "qcu",
    question: "Quel widget est généralement utilisé comme racine d'une application Flutter Material Design ?",
    options: [
      "A. Scaffold",
      "B. MaterialApp",
      "C. Container",
      "D. Column",
    ],
    answers: ["B"],
  },
  {
    number: 16,
    type: "qcu",
    question: "Quelle est la fonction principale de Scaffold ?",
    options: [
      "A. Gérer les thèmes",
      "B. Fournir la structure de base d'une page (AppBar, body, etc.)",
      "C. Gérer la navigation",
      "D. Afficher des listes",
    ],
    answers: ["B"],
  },
  {
    number: 17,
    type: "qcu",
    question: "Comment accéder au contexte (BuildContext) dans la méthode build() ?",
    options: [
      "A. Via une variable globale",
      "B. C'est un paramètre de la méthode build()",
      "C. Via this.context",
      "D. Via BuildContext.current",
    ],
    answers: ["B"],
  },
  {
    number: 18,
    type: "qcu",
    question: "Quelle méthode permet de reconstruire l'interface dans un StatefulWidget ?",
    options: [
      "A. rebuild()",
      "B. update()",
      "C. setState()",
      "D. refresh()",
    ],
    answers: ["C"],
  },
  {
    number: 19,
    type: "qcu",
    question: "Dans l'arbre de widgets, quel est le parent typique de Scaffold ?",
    options: [
      "A. MaterialApp",
      "B. Container",
      "C. Column",
      "D. AppBar",
    ],
    answers: ["A"],
  },
  {
    number: 20,
    type: "qcu",
    question: "Que retourne obligatoirement la méthode build() ?",
    options: [
      "A. void",
      "B. Widget",
      "C. State",
      "D. BuildContext",
    ],
    answers: ["B"],
  },
  {
    number: 21,
    type: "qcu",
    question: "Comment centrer un widget horizontalement dans une Row ?",
    options: [
      "A. Row(alignment: Alignment.center, children: [...])",
      "B. Row(mainAxisAlignment: MainAxisAlignment.center, children: [...])",
      "C. Row(crossAxisAlignment: CrossAxisAlignment.center, children: [...])",
      "D. Row(justify: Justify.center, children: [...])",
    ],
    answers: ["B"],
  },
  {
    number: 22,
    type: "qcu",
    question: "Quelle est la différence entre mainAxisAlignment et crossAxisAlignment dans une Column ?",
    options: [
      "A. mainAxisAlignment : horizontal, crossAxisAlignment : vertical",
      "B. mainAxisAlignment : vertical, crossAxisAlignment : horizontal",
      "C. Les deux contrôlent l'alignement horizontal",
      "D. Les deux contrôlent l'alignement vertical",
    ],
    answers: ["B"],
  },
  {
    number: 23,
    type: "qcu",
    question: "Comment faire en sorte qu'un widget occupe tout l'espace disponible dans une Row ?",
    options: [
      "A. Flexible(child: monWidget)",
      "B. Expanded(child: monWidget)",
      "C. Stretched(child: monWidget)",
      "D. FullWidth(child: monWidget)",
    ],
    answers: ["B"],
  },
  {
    number: 24,
    type: "qcu",
    question: "Quelle propriété de Container permet d'ajouter un espacement intérieur ?",
    options: [
      "A. margin",
      "B. padding",
      "C. spacing",
      "D. insets",
    ],
    answers: ["B"],
  },
  {
    number: 25,
    type: "qcu",
    question: "Comment créer un bouton surélevé en Flutter ?",
    options: [
      "A. TextButton(onPressed: (){}, child: Text(\"OK\"))",
      "B. ElevatedButton(onPressed: (){}, child: Text(\"OK\"))",
      "C. RaisedButton(onPressed: (){}, child: Text(\"OK\"))",
      "D. Button.elevated(onPressed: (){}, child: Text(\"OK\"))",
    ],
    answers: ["B"],
  },
  {
    number: 26,
    type: "qcu",
    question: "Quelle est la syntaxe correcte pour afficher une image depuis les assets ?",
    options: [
      "A. Image.asset('assets/images/logo.png')",
      "B. Image.file('assets/images/logo.png')",
      "C. Image.network('assets/images/logo.png')",
      "D. Asset.image('assets/images/logo.png')",
    ],
    answers: ["A"],
  },
  {
    number: 27,
    type: "qcu",
    question: "Comment récupérer le texte saisi dans un TextField ?",
    options: [
      "A. Via la propriété value du TextField",
      "B. Via un TextEditingController",
      "C. Via TextField.getText()",
      "D. Via BuildContext.getText()",
    ],
    answers: ["B"],
  },
  {
    number: 28,
    type: "qcu",
    question: "Quelle propriété de ListView.builder détermine le nombre d'éléments ?",
    options: [
      "A. length",
      "B. count",
      "C. itemCount",
      "D. size",
    ],
    answers: ["C"],
  },
  {
    number: 29,
    type: "qcu",
    question: "Comment valider un formulaire avec le widget Form ?",
    options: [
      "A. Form.validate()",
      "B. FormState.currentState.validate()",
      "C. Via une GlobalKey<FormState> et key.currentState!.validate()",
      "D. Form.check()",
    ],
    answers: ["C"],
  },
  {
    number: 30,
    type: "qcu",
    question: "Quelle est la différence principale entre ListView et ListView.builder ?",
    options: [
      "A. ListView.builder est plus rapide pour de grandes listes",
      "B. ListView ne peut afficher que du texte",
      "C. ListView.builder ne peut pas défiler",
      "D. Il n'y a aucune différence",
    ],
    answers: ["A"],
  },
  {
    number: 31,
    type: "qcu",
    question: "Comment naviguer vers une nouvelle page en Flutter ?",
    options: [
      "A. Navigator.push(context, MaterialPageRoute(builder: (context)=> NouvellePage()))",
      "B. Router.push(context, NouvellePage())",
      "C. Navigate.to(context, NouvellePage())",
      "D. PageRouter.navigate(context, NouvellePage())",
    ],
    answers: ["A"],
  },
  {
    number: 32,
    type: "qcu",
    question: "Comment revenir à la page précédente ?",
    options: [
      "A. Navigator.back(context)",
      "B. Navigator.pop(context)",
      "C. Router.pop(context)",
      "D. Navigator.goBack(context)",
    ],
    answers: ["B"],
  },
  {
    number: 33,
    type: "qcu",
    question: "Comment passer des données à une nouvelle page lors de la navigation ?",
    options: [
      "A. Via des variables globales",
      "B. Via le constructeur de la nouvelle page",
      "C. Via une base de données",
      "D. Via des fichiers temporaires",
    ],
    answers: ["B"],
  },
  {
    number: 34,
    type: "qcu",
    question: "Quelle méthode permet de naviguer vers une route nommée ?",
    options: [
      "A. Navigator.push(context, '/maRoute')",
      "B. Navigator.pushNamed(context, '/maRoute')",
      "C. Navigator.goTo(context, '/maRoute')",
      "D. Navigator.route(context, '/maRoute')",
    ],
    answers: ["B"],
  },
  {
    number: 35,
    type: "qcu",
    question: "Comment récupérer une valeur de retour d'une page qui se ferme ?",
    options: [
      "A. Via une callback function",
      "B. Navigator.push() retourne un Future",
      "C. Via une variable globale",
      "D. Via SharedPreferences",
    ],
    answers: ["B"],
  },
  {
    number: 36,
    type: "qcu",
    question: "Quelle est la principale différence entre StatelessWidget et StatefulWidget ?",
    options: [
      "A. StatelessWidget est plus rapide",
      "B. StatefulWidget peut modifier son état et se reconstruire",
      "C. StatelessWidget ne peut contenir de données",
      "D. StatefulWidget ne peut pas avoir de constructeur",
    ],
    answers: ["B"],
  },
  {
    number: 37,
    type: "qcu",
    question: "Que fait exactement setState() ?",
    options: [
      "A. Sauvegarde l'état en base de données",
      "B. Marque le widget comme devant être reconstruit",
      "C. Redémarre l'application",
      "D. Vide le cache",
    ],
    answers: ["B"],
  },
  {
    number: 38,
    type: "qcu",
    question: "Où doit-on appeler setState() ?",
    options: [
      "A. Dans initState()",
      "B. Dans build()",
      "C. Dans les méthodes qui modifient l'état",
      "D. Dans dispose()",
    ],
    answers: ["C"],
  },
  {
    number: 39,
    type: "qcu",
    question: "Que se passe-t-il si on appelle setState() après dispose() ?",
    options: [
      "A. Rien de particulier",
      "B. Une exception est levée",
      "C. L'état est restauré",
      "D. L'application redémarre",
    ],
    answers: ["B"],
  },
  {
    number: 40,
    type: "qcu",
    question: "Pourquoi ne doit-on pas faire d'opérations coûteuses dans build() ?",
    options: [
      "A. Cela consomme trop de mémoire",
      "B. build() peut être appelée fréquemment",
      "C. Cela provoque des erreurs",
      "D. C'est interdit par Flutter",
    ],
    answers: ["B"],
  },
  {
    number: 41,
    type: "qcu",
    question: "Comment personnaliser le thème global d'une application Flutter ?",
    options: [
      "A. Via la propriété theme de MaterialApp",
      "B. Via un fichier CSS",
      "C. Via ThemeManager.setGlobal()",
      "D. Via les SharedPreferences",
    ],
    answers: ["A"],
  },
  {
    number: 42,
    type: "qcu",
    question: "Quelle propriété de Container permet d'arrondir les coins ?",
    options: [
      "A. borderRadius directement",
      "B. decoration: BoxDecoration(borderRadius: ...)",
      "C. cornerRadius",
      "D. rounded: true",
    ],
    answers: ["B"],
  },
  {
    number: 43,
    type: "qcu",
    question: "Dans quel fichier ajoute-t-on les dépendances d'un projet Flutter ?",
    options: [
      "A. dependencies.yaml",
      "B. pubspec.yaml",
      "C. packages.json",
      "D. build.gradle",
    ],
    answers: ["B"],
  },
  {
    number: 44,
    type: "qcu",
    question: "Où place-t-on généralement les images dans un projet Flutter ?",
    options: [
      "A. lib/images/",
      "B. assets/images/",
      "C. resources/images/",
      "D. public/images/",
    ],
    answers: ["B"],
  },
  {
    number: 45,
    type: "qcu",
    question: "Quelle commande permet d'installer les packages après modification de pubspec.yaml ?",
    options: [
      "A. flutter install",
      "B. flutter pub get",
      "C. flutter packages install",
      "D. flutter dependencies",
    ],
    answers: ["B"],
  },
  {
    number: 46,
    type: "qcu",
    question: "Comment déclarer une fonction asynchrone en Dart ?",
    options: [
      "A. async function maFonction(){}",
      "B. Future maFonction()async {}",
      "C. void maFonction()async {}",
      "D. async void maFonction(){}",
    ],
    answers: ["C"],
  },
  {
    number: 47,
    type: "qcu",
    question: "Que fait le mot-clé await ?",
    options: [
      "A. Attend qu'une fonction soit définie",
      "B. Attend le résultat d'une opération asynchrone",
      "C. Met en pause l'application",
      "D. Attend une interaction utilisateur",
    ],
    answers: ["B"],
  },
  {
    number: 48,
    type: "qcu",
    question: "Comment effectuer un appel HTTP GET avec le package http ?",
    options: [
      "A. http.get(Uri.parse('https://api.exemple.com'))",
      "B. http.request('GET', 'https://api.exemple.com')",
      "C. http.fetch('https://api.exemple.com')",
      "D. http.call('https://api.exemple.com')",
    ],
    answers: ["A"],
  },
  {
    number: 49,
    type: "qcu",
    question: "Comment parser une réponse JSON en Dart ?",
    options: [
      "A. JSON.parse(response.body)",
      "B. json.decode(response.body)",
      "C. jsonDecode(response.body)",
      "D. response.body.toJson()",
    ],
    answers: ["B"],
  },
  {
    number: 50,
    type: "qcu",
    question: "Dans un FutureBuilder, que représente snapshot.hasData ?",
    options: [
      "A. Si la Future s'est terminée avec succès",
      "B. Si des données sont disponibles (non-null)",
      "C. Si la connexion est active",
      "D. Si il y a une erreur",
    ],
    answers: ["B"],
  }
];